# Generated by Django 4.2 on 2023-05-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50, verbose_name='Material')),
                ('short_description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('sample_picture', models.ImageField(blank=True, default='', upload_to='projects/materials/%Y/%m/%d/', verbose_name='Foto de exemplo')),
            ],
        ),
    ]
