# Generated by Django 4.2 on 2023-04-16 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('thumbnail', models.ImageField(blank=True, default='', upload_to='projects/cover/%Y/%m/%d/', verbose_name='Foto de capa')),
                ('pictures', models.FileField(upload_to='', verbose_name='Fotos do projeto')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
