# Generated by Django 4.2 on 2023-04-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pictures',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='Fotos do projeto'),
        ),
    ]
