# Generated by Django 4.2 on 2023-04-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(upload_to='projects/images/', verbose_name='Fotos do projeto')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='pictures',
        ),
        migrations.AddField(
            model_name='project',
            name='pictures',
            field=models.ManyToManyField(to='projects.pictures'),
        ),
    ]
