# Generated by Django 4.2 on 2023-04-17 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pictures_remove_project_pictures_project_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pictures',
        ),
        migrations.AddField(
            model_name='pictures',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='projects/images/'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
