# Generated by Django 4.2 on 2023-04-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_messages_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='phone',
        ),
        migrations.AddField(
            model_name='messages',
            name='subject',
            field=models.CharField(default='', max_length=100, verbose_name='Assunto'),
            preserve_default=False,
        ),
    ]
